apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "http://100.68.167.74:5000/rafaelremondes/demo:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "http://100.68.167.74:5000/rafaelremondes/demo/rafaelremondes/demo:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: demo
        chartPath: charts/demo
        setValueTemplates:
          image.repository: "http://100.68.167.74:5000/rafaelremondes/demo/rafaelremondes/demo"
          image.tag: "{{.TAG}}"
